/**
 * Note · the single data primitive of Loom's unified Personal Layer × View
 * architecture. Committed 2026-04-12 after 16 rounds of design refinement.
 *
 * See memory/project_loom_unified_architecture.md for the full architecture.
 * See memory/feedback_learn_not_organize.md for the north star principles
 * this type structurally guarantees (user edit rights, zero organization,
 * etc.)
 *
 * Every user-created thing in Loom is a Note. Thought-anchors, reconstructions,
 * annotations, captures, and highlights are ALL just Notes with different
 * `anchor` targets, content, and flags. Source files themselves are NOT
 * mutated — annotations live beside them.
 *
 * Notes are append-only. Editing a Note means appending a new Note with
 * `flags.supersedes = oldId`. Deletion means marking with a delete flag,
 * never destroying.
 *
 * This file defines TYPES ONLY. The actual storage, query, and adapter
 * logic lives in neighboring files:
 *   - store.ts    — future: IndexedDB append-only store
 *   - query.ts    — filter/sort primitives
 *   - from-trace.ts — read existing trace events as Notes (adapter)
 */

/**
 * Stable id. Format: `nt_<timestamp>_<rand>`. Generated by newNoteId().
 * For Notes synthesized from existing trace events (via from-trace.ts),
 * the id is derived from the source event so repeated reads return the
 * same Note id — important for React keys and diffing.
 */
export type NoteId = string;

/**
 * A doc-like thing a Note can anchor to. Currently:
 *   - `wiki/<slug>` — wiki chapter
 *   - `know/<id>` — knowledge doc
 *   - `uploaded/<id>` — future: ingested material
 * Parses to the same shape as `Trace.source.docId` so existing store
 * infrastructure works unchanged.
 */
export type SourceDocId = string;

/**
 * A Note's anchor tells Loom WHERE it belongs.
 *
 * `target` is the thing this Note is attached to:
 *   - A SourceDocId — this Note is about a passage (or the whole) of a doc
 *   - A NoteId — this Note is a sub-annotation on another Note (fractal)
 *   - null — free-floating Note with no anchor (rare; used for scratch-space
 *     thoughts that don't belong to any particular doc)
 *
 * `range` optionally narrows to a char range within the target. If omitted,
 * the Note anchors to the whole target (e.g., a reconstruction of an entire
 * doc has target=SourceDocId and range=undefined).
 *
 * `blockText` is a stable text fingerprint used to re-resolve the anchor
 * if the target's DOM/markdown reindexes. Without this, char ranges become
 * ambiguous across reloads. Mirrors the existing thought-anchor model.
 */
export type NoteAnchor = Omit<SourceAnchor, 'page'> & {
  target: SourceDocId | NoteId | null;
  /** The raw quoted text at the anchor's range, if any. */
  quote?: string;
  /** Optional char range within the target. Omit for whole-target anchor. */
  range?: { charStart: number; charEnd: number };
};

/**
 * Optional boolean/pointer flags that modify a Note's semantics.
 * All flags are optional. A Note with no flags is an ordinary note.
 *
 * Note on "source editing": the user explicitly confirmed 2026-04-12 that
 * Loom does NOT need to mutate canonical source documents. "User editing
 * rights" (north star clause D/E) means the user can annotate, question,
 * and take notes on source — which the existing thought-anchor + capture
 * flow already covers completely. No source-edit overlay flag is needed.
 */
export type NoteFlags = {
  /**
   * If set, this Note replaces an earlier Note in the rendered view.
   * The earlier Note remains in the append-only log (for history), but
   * queries that "get current state" should prefer the superseding version.
   * Used for user edits of prior Notes (theirs or AI-generated).
   */
  supersedes?: NoteId;

  /**
   * If true, this Note is "locked" as verified/final. Set automatically
   * when Phase 5 AI examiner finishes asking detail questions without
   * finding gaps, or manually by the user. Crystallized Notes cannot be
   * superseded without first unlocking.
   */
  crystallized?: boolean;

  /**
   * If true, this Note is a soft-delete marker. The superseded Note(s)
   * at the same anchor are hidden from current-state queries but remain
   * in the log. Distinguished from normal supersedes because content is
   * empty and render should show nothing (or a "deleted" placeholder).
   */
  deleted?: boolean;
};

/**
 * A Note · Loom's single user-created data type.
 *
 * Construction:
 *   - By user action (capture, ChatFocus commit, rehearsal typing)
 *   - By synthesis from existing trace events (via from-trace.ts adapter)
 *
 * Lifecycle: append-only. Never mutated after creation.
 */
export type Note = {
  id: NoteId;
  anchor: NoteAnchor;
  /** Markdown + LaTeX. Empty string is valid (e.g., capture with no elaboration yet). */
  content: string;
  /** Optional short summary derived from content. Used in overview/list views. */
  summary?: string;
  flags: NoteFlags;
  /** Timestamp of creation. Notes are sorted by `at` within an anchor. */
  at: number;
  /**
   * The trace id this Note was synthesized from (when adapted from an
   * existing trace event). Allows round-tripping Notes back to trace
   * events for legacy code paths. Absent for natively-created Notes
   * once the write path (store.ts) is implemented.
   */
  __traceId?: string;
};

/**
 * Generate a new Note id. Used when writing a native Note (not adapted
 * from an existing trace event).
 */
export function newNoteId(): NoteId {
  const ts = Date.now().toString(36);
  const rand = Math.random().toString(36).slice(2, 8);
  return `nt_${ts}_${rand}`;
}

/**
 * Derive a deterministic Note id from a trace event's (traceId, at) pair.
 * Used by from-trace.ts so the same trace event always projects to the
 * same Note id — critical for React diffing and stable references.
 */
export function deriveNoteIdFromTraceEvent(traceId: string, at: number, kindTag: string = 'ta'): NoteId {
  return `nt_${kindTag}_${traceId.slice(2, 10)}_${at.toString(36)}`;
}
import type { SourceAnchor } from '../trace/types';
