// Capture snapshot CTA contract — pins the 2026-05-02 fix for
// "Open full snapshot" CTA producing no interaction. Root cause was the
// snapshotHref pointing at `loom://bundle/loom-render/snapshot/?…`,
// a Next.js route that was never implemented (no
// `app/loom-render/snapshot/page.tsx` ever shipped). Clicking the CTA
// navigated to a missing bundle path and silently failed.
//
// The fix routes directly at the saved snapshot HTML on disk via the
// existing `loom://content/<root>/sub/<subPath>/<filename>` content
// scheme, which the Swift LoomURLSchemeHandler already serves.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

function read(relative: string): string {
  return fs.readFileSync(path.join(repoRoot, relative), 'utf8');
}

test('snapshot CTA does NOT construct a /loom-render/snapshot/ bundle URL at runtime', () => {
  const source = read('app/loom-render/capture/page.tsx');
  // The dead route was generated by a template literal returning a
  // `loom://bundle/loom-render/snapshot/?<qs>` string. Refuse to let
  // that runtime construction come back. (Documentation comments
  // referencing the historical bug are fine — we only forbid the
  // active code path that builds the URL.)
  assert.doesNotMatch(source, /return\s+`loom:\/\/bundle\/loom-render\/snapshot\//);
  assert.doesNotMatch(source, /href=\{?["']loom:\/\/bundle\/loom-render\/snapshot\//);
});

test('snapshot CTA resolves to loom://content/<root>/sub/<subPath>/<filename>', () => {
  const source = read('app/loom-render/capture/page.tsx');
  // The fix builds a `loom://content/<rootParam>…/<snapshotFilename>` URL.
  const hrefBlockStart = source.indexOf('const snapshotHref = useMemo');
  assert.ok(hrefBlockStart > 0, 'snapshotHref useMemo missing');
  const hrefBlockEnd = source.indexOf('}, [', hrefBlockStart);
  assert.ok(hrefBlockEnd > hrefBlockStart, 'snapshotHref useMemo close missing');
  const hrefBody = source.slice(hrefBlockStart, hrefBlockEnd);
  assert.match(hrefBody, /loom:\/\/content\/\$\{rootParam\}/);
  assert.match(hrefBody, /\$\{snapshotFilename\}/);
});

test('there is no app/loom-render/snapshot/page.tsx route to navigate to (justifies the redirect to content URL)', () => {
  const snapshotPagePath = path.join(repoRoot, 'app/loom-render/snapshot/page.tsx');
  // If a future change ships an actual snapshot route, this test should
  // be revisited (the redirect to content URL becomes redundant).
  assert.equal(fs.existsSync(snapshotPagePath), false);
});
