// AUTO-GENERATED by scripts/ingest-knowledge.ts
export type KnowledgeSub = { label: string; order: number; count: number };
export type KnowledgeCategory = { slug: string; label: string; count: number; subs: KnowledgeSub[] };
export const knowledgeCategories: KnowledgeCategory[] = [
  {
    "slug": "openclaw",
    "label": "OpenClaw",
    "count": 1,
    "subs": [
      {
        "label": "",
        "order": 9999,
        "count": 1
      }
    ]
  },
  {
    "slug": "unsw-comm-3030",
    "label": "UNSW · COMM 3030",
    "count": 74,
    "subs": [
      {
        "label": "Week 0",
        "order": 0,
        "count": 1
      },
      {
        "label": "Week 1",
        "order": 1,
        "count": 2
      },
      {
        "label": "Week 1 / Module 1 - Introduction to Course and Social Entrepreneurship",
        "order": 1,
        "count": 3
      },
      {
        "label": "Week 1 / Module 2 - Measuring and Demonstrating Social Impact",
        "order": 1,
        "count": 1
      },
      {
        "label": "Week 1 / Module 2 - Measuring and Demonstrating Social Impact / The Designing for Growth Field Book",
        "order": 1,
        "count": 4
      },
      {
        "label": "Week 1 / Module 2 - Measuring and Demonstrating Social Impact / The Designing for Growth Field Book / The Steps",
        "order": 1,
        "count": 15
      },
      {
        "label": "Week 1 / Module 2 - Measuring and Demonstrating Social Impact / The Designing for Growth Field Book / The Tools",
        "order": 1,
        "count": 23
      },
      {
        "label": "Week 2",
        "order": 2,
        "count": 3
      },
      {
        "label": "Week 2 / Module 3 - Introduction to Project Management and Consulting",
        "order": 2,
        "count": 4
      },
      {
        "label": "Week 2 / Module 4 - Value Proposition and Purpose-Driven Marketing for Social Enterprises",
        "order": 2,
        "count": 1
      },
      {
        "label": "Week 2 / Module 4 - Value Proposition and Purpose-Driven Marketing for Social Enterprises / Value Proposition Design",
        "order": 2,
        "count": 4
      },
      {
        "label": "Week 3",
        "order": 3,
        "count": 3
      },
      {
        "label": "Week 3 / Module 5 - Design Thinking and Systems Thinking",
        "order": 3,
        "count": 2
      },
      {
        "label": "Week 3 / Module 6 - Report Writing Skills Workshop",
        "order": 3,
        "count": 2
      },
      {
        "label": "",
        "order": 9999,
        "count": 1
      },
      {
        "label": "Surf Life Saving Sydney",
        "order": 9999,
        "count": 5
      }
    ]
  },
  {
    "slug": "unsw-econ-3202",
    "label": "UNSW · ECON 3202",
    "count": 37,
    "subs": [
      {
        "label": "Week / W1",
        "order": 1,
        "count": 6
      },
      {
        "label": "Week / W2",
        "order": 2,
        "count": 4
      },
      {
        "label": "Week / W3",
        "order": 3,
        "count": 4
      },
      {
        "label": "Week / W4",
        "order": 4,
        "count": 4
      },
      {
        "label": "Week / W5",
        "order": 5,
        "count": 4
      },
      {
        "label": "Week / W7",
        "order": 7,
        "count": 4
      },
      {
        "label": "Week / W8",
        "order": 8,
        "count": 3
      },
      {
        "label": "",
        "order": 9999,
        "count": 3
      },
      {
        "label": "Problem Set Submission",
        "order": 9999,
        "count": 5
      }
    ]
  },
  {
    "slug": "unsw-fins-3616",
    "label": "UNSW · FINS 3616",
    "count": 39,
    "subs": [
      {
        "label": "Week 01",
        "order": 1,
        "count": 4
      },
      {
        "label": "Week 02",
        "order": 2,
        "count": 4
      },
      {
        "label": "Week 03",
        "order": 3,
        "count": 4
      },
      {
        "label": "Week 04",
        "order": 4,
        "count": 4
      },
      {
        "label": "Week 05",
        "order": 5,
        "count": 3
      },
      {
        "label": "Week 07",
        "order": 7,
        "count": 3
      },
      {
        "label": "Week 08",
        "order": 8,
        "count": 3
      },
      {
        "label": "Week 09",
        "order": 9,
        "count": 3
      },
      {
        "label": "Week 10",
        "order": 10,
        "count": 3
      },
      {
        "label": "FInal",
        "order": 9999,
        "count": 2
      },
      {
        "label": "iLab",
        "order": 9999,
        "count": 3
      },
      {
        "label": "Individual",
        "order": 9999,
        "count": 3
      }
    ]
  },
  {
    "slug": "unsw-fins-3635",
    "label": "UNSW · FINS 3635",
    "count": 32,
    "subs": [
      {
        "label": "Week 01",
        "order": 1,
        "count": 5
      },
      {
        "label": "A2",
        "order": 2,
        "count": 4
      },
      {
        "label": "Week 02",
        "order": 2,
        "count": 5
      },
      {
        "label": "Week 03",
        "order": 3,
        "count": 3
      },
      {
        "label": "Week 04",
        "order": 4,
        "count": 4
      },
      {
        "label": "Week 05",
        "order": 5,
        "count": 2
      },
      {
        "label": "Week 07",
        "order": 7,
        "count": 3
      },
      {
        "label": "Week 08",
        "order": 8,
        "count": 2
      },
      {
        "label": "Week 09",
        "order": 9,
        "count": 3
      },
      {
        "label": "Week 10",
        "order": 10,
        "count": 1
      }
    ]
  },
  {
    "slug": "unsw-fins-3640",
    "label": "UNSW · FINS 3640",
    "count": 53,
    "subs": [
      {
        "label": "Week 0",
        "order": 0,
        "count": 3
      },
      {
        "label": "Week 0 / Python Installation Steps",
        "order": 0,
        "count": 3
      },
      {
        "label": "Assessment 1",
        "order": 1,
        "count": 1
      },
      {
        "label": "Assessment 1 / HW1",
        "order": 1,
        "count": 1
      },
      {
        "label": "Week 1&2",
        "order": 1,
        "count": 5
      },
      {
        "label": "Week 1&2 / Python Applications (Weeks 1  2)",
        "order": 1,
        "count": 1
      },
      {
        "label": "Assessment 2",
        "order": 2,
        "count": 3
      },
      {
        "label": "Week 3",
        "order": 3,
        "count": 4
      },
      {
        "label": "Week 4",
        "order": 4,
        "count": 5
      },
      {
        "label": "Week 5",
        "order": 5,
        "count": 3
      },
      {
        "label": "Week 6",
        "order": 6,
        "count": 4
      },
      {
        "label": "Week 6 / Python Applications Lecturea 6  7",
        "order": 6,
        "count": 5
      },
      {
        "label": "Week 6 / Recommended exercise Python Solutions",
        "order": 6,
        "count": 3
      },
      {
        "label": "Week 7",
        "order": 7,
        "count": 1
      },
      {
        "label": "Week 8",
        "order": 8,
        "count": 5
      },
      {
        "label": "Week 8 / Python Recommended Exercises",
        "order": 8,
        "count": 2
      },
      {
        "label": "Week 9",
        "order": 9,
        "count": 4
      }
    ]
  },
  {
    "slug": "unsw-fins-3646",
    "label": "UNSW · FINS 3646",
    "count": 81,
    "subs": [
      {
        "label": "INFS 2822",
        "order": 2822,
        "count": 12
      },
      {
        "label": "INFS 2822 / Recommened Reading",
        "order": 2822,
        "count": 3
      },
      {
        "label": "FINS3646",
        "order": 3646,
        "count": 2
      },
      {
        "label": "FINS3646 / Project / Project 1 / Project example",
        "order": 3646,
        "count": 1
      },
      {
        "label": "FINS3646 / Project / Project 1 / project1 / data",
        "order": 3646,
        "count": 25
      },
      {
        "label": "FINS3646 / toolkit / data",
        "order": 3646,
        "count": 2
      },
      {
        "label": "FINS3646 / toolkit / event_study / data",
        "order": 3646,
        "count": 3
      },
      {
        "label": "FINS3646 / toolkit / projects / project0 / _solution",
        "order": 3646,
        "count": 1
      },
      {
        "label": "FINS3646 / toolkit / projects / project0 / data",
        "order": 3646,
        "count": 2
      },
      {
        "label": "FINS3646 / toolkit / projects / project2 / data",
        "order": 3646,
        "count": 3
      },
      {
        "label": "FINS3646 / Week 1",
        "order": 3646,
        "count": 4
      },
      {
        "label": "FINS3646 / Week 2",
        "order": 3646,
        "count": 5
      },
      {
        "label": "FINS3646 / Week 2 / Lecture Discussion Problems",
        "order": 3646,
        "count": 3
      },
      {
        "label": "FINS3646 / Week 3",
        "order": 3646,
        "count": 4
      },
      {
        "label": "FINS3646 / Week 4",
        "order": 3646,
        "count": 7
      },
      {
        "label": "FINS3646 / Week 5",
        "order": 3646,
        "count": 4
      }
    ]
  },
  {
    "slug": "unsw-fins-3666",
    "label": "UNSW · FINS 3666",
    "count": 101,
    "subs": [
      {
        "label": "A1 Activity 1",
        "order": 1,
        "count": 7
      },
      {
        "label": "A1 Activity 1 / output",
        "order": 1,
        "count": 1
      },
      {
        "label": "A1 Activity 1 / output / data",
        "order": 1,
        "count": 7
      },
      {
        "label": "A1 Activity 1 / output / report",
        "order": 1,
        "count": 1
      },
      {
        "label": "A1 Activity 2",
        "order": 1,
        "count": 1
      },
      {
        "label": "A1 Activity 2 / Assessment 1, Activity 2 Materials-20260207",
        "order": 1,
        "count": 1
      },
      {
        "label": "A1 Activity 2 / Assessment 1, Activity 2 Materials-20260207 / Ass 1, Activity 2 Data",
        "order": 1,
        "count": 4
      },
      {
        "label": "A1 Activity 2 / Assessment 1, Activity 2 Materials-20260207 / Ass 1, Activity 2 Instructions",
        "order": 1,
        "count": 1
      },
      {
        "label": "A1 Activity 2 / Cleaned_Data",
        "order": 1,
        "count": 2
      },
      {
        "label": "A1 Activity 2 / Code",
        "order": 1,
        "count": 2
      },
      {
        "label": "A1 Activity 2 / output / data",
        "order": 1,
        "count": 9
      },
      {
        "label": "A1 Activity 2 / output / report",
        "order": 1,
        "count": 1
      },
      {
        "label": "A1 Activity 3",
        "order": 1,
        "count": 2
      },
      {
        "label": "A1 Activity 3 / Activity 3 Cleaned Data",
        "order": 1,
        "count": 4
      },
      {
        "label": "A1 Activity 3 / Activity 3 Code",
        "order": 1,
        "count": 2
      },
      {
        "label": "A1 Activity 3 / Activity 3 Data",
        "order": 1,
        "count": 4
      },
      {
        "label": "A1 Activity 3 / output / data",
        "order": 1,
        "count": 9
      },
      {
        "label": "A1 Activity 3 / output / report",
        "order": 1,
        "count": 1
      },
      {
        "label": "Week 01",
        "order": 1,
        "count": 2
      },
      {
        "label": "Week 01 / Recommended Readings",
        "order": 1,
        "count": 4
      },
      {
        "label": "Assessment 2",
        "order": 2,
        "count": 3
      },
      {
        "label": "Assessment 2 / Data",
        "order": 2,
        "count": 11
      },
      {
        "label": "Assessment 2 / output / data",
        "order": 2,
        "count": 8
      },
      {
        "label": "Assessment 2 / output / report",
        "order": 2,
        "count": 4
      },
      {
        "label": "Week 02",
        "order": 2,
        "count": 1
      },
      {
        "label": "Week 03",
        "order": 3,
        "count": 1
      },
      {
        "label": "Week 04",
        "order": 4,
        "count": 1
      },
      {
        "label": "Week 07",
        "order": 7,
        "count": 1
      },
      {
        "label": "Week 08",
        "order": 8,
        "count": 1
      },
      {
        "label": "Week 09",
        "order": 9,
        "count": 1
      },
      {
        "label": "Week 10",
        "order": 10,
        "count": 2
      },
      {
        "label": "",
        "order": 9999,
        "count": 2
      }
    ]
  },
  {
    "slug": "unsw-infs-3822",
    "label": "UNSW · INFS 3822",
    "count": 94,
    "subs": [
      {
        "label": "Assessment  / Assessment 1",
        "order": 1,
        "count": 3
      },
      {
        "label": "Week / Week 1",
        "order": 1,
        "count": 4
      },
      {
        "label": "Assessment  / Assessment 2",
        "order": 2,
        "count": 5
      },
      {
        "label": "Week / Week 2",
        "order": 2,
        "count": 6
      },
      {
        "label": "Week / Week 2 / tm-my-image-model",
        "order": 2,
        "count": 2
      },
      {
        "label": "Week / Week 3",
        "order": 3,
        "count": 5
      },
      {
        "label": "Week / Week 3 / Colab Notebooks-20260303",
        "order": 3,
        "count": 4
      },
      {
        "label": "Week / Week 3 / Datasets-20260303",
        "order": 3,
        "count": 4
      },
      {
        "label": "Week / Week 3 / Hands-On Activities",
        "order": 3,
        "count": 3
      },
      {
        "label": "Week / Week 4",
        "order": 4,
        "count": 6
      },
      {
        "label": "Week / Week 4 / A Comprehensive Guide in Python and R including all steps required to build ML Models-20260310",
        "order": 4,
        "count": 8
      },
      {
        "label": "Week / Week 4 / Colab Notebooks-20260310",
        "order": 4,
        "count": 14
      },
      {
        "label": "Week / Week 4 / Datasets-20260310",
        "order": 4,
        "count": 1
      },
      {
        "label": "Week / Week 4 / Pre-trained model files (for Hands-On Exercise 1)-20260310",
        "order": 4,
        "count": 1
      },
      {
        "label": "Week / Week 5",
        "order": 5,
        "count": 5
      },
      {
        "label": "Week / Week 5 / Week 5 Hands-On Activities",
        "order": 5,
        "count": 11
      },
      {
        "label": "Week / Week 7",
        "order": 7,
        "count": 4
      },
      {
        "label": "Week / Week 8",
        "order": 8,
        "count": 5
      },
      {
        "label": "",
        "order": 9999,
        "count": 3
      }
    ]
  },
  {
    "slug": "unsw-math-1141",
    "label": "UNSW · MATH 1141",
    "count": 5,
    "subs": [
      {
        "label": "",
        "order": 9999,
        "count": 4
      },
      {
        "label": "Maple",
        "order": 9999,
        "count": 1
      }
    ]
  },
  {
    "slug": "unsw-math-1241",
    "label": "UNSW · MATH 1241",
    "count": 4,
    "subs": [
      {
        "label": "",
        "order": 9999,
        "count": 4
      }
    ]
  },
  {
    "slug": "unsw-math-2018",
    "label": "UNSW · MATH 2018",
    "count": 61,
    "subs": [
      {
        "label": "",
        "order": 9999,
        "count": 1
      },
      {
        "label": "Lecture Notes-20260108",
        "order": 20260108,
        "count": 2
      },
      {
        "label": "Lecture Notes-20260108 / First year MATH 1A and 1B notes",
        "order": 20260108,
        "count": 4
      },
      {
        "label": "Lecture Notes-20260108 / MATH2019 lecture notes",
        "order": 20260108,
        "count": 9
      },
      {
        "label": "Lecture Notes-20260108 / Topic 1",
        "order": 20260108,
        "count": 4
      },
      {
        "label": "Lecture Notes-20260108 / Topic 2",
        "order": 20260108,
        "count": 4
      },
      {
        "label": "Lecture Notes-20260108 / Topic 3",
        "order": 20260108,
        "count": 4
      },
      {
        "label": "Lecture Notes-20260108 / Topic 4",
        "order": 20260108,
        "count": 4
      },
      {
        "label": "Lecture Notes-20260108 / Topic 5",
        "order": 20260108,
        "count": 4
      },
      {
        "label": "Lecture Notes-20260108 / Topic 6",
        "order": 20260108,
        "count": 5
      },
      {
        "label": "Lecture Notes-20260108 / Topic 7",
        "order": 20260108,
        "count": 7
      },
      {
        "label": "Lecture Notes-20260108 / Topic 8",
        "order": 20260108,
        "count": 7
      },
      {
        "label": "Lecture Notes-20260108 / Topic 9",
        "order": 20260108,
        "count": 6
      }
    ]
  },
  {
    "slug": "unsw-math-2089",
    "label": "UNSW · MATH 2089",
    "count": 1,
    "subs": [
      {
        "label": "Numericial Methods / Matlab",
        "order": 9999,
        "count": 1
      }
    ]
  },
  {
    "slug": "unsw-math-2901",
    "label": "UNSW · MATH 2901",
    "count": 29,
    "subs": [
      {
        "label": "Assessments Hub / Class test 1",
        "order": 1,
        "count": 1
      },
      {
        "label": "Assessments Hub / Class test 2",
        "order": 2,
        "count": 1
      },
      {
        "label": "Assessments Hub / Midterm test / 2024",
        "order": 2024,
        "count": 4
      },
      {
        "label": "Assessments Hub / Midterm test / 2025",
        "order": 2025,
        "count": 4
      },
      {
        "label": "",
        "order": 9999,
        "count": 1
      },
      {
        "label": "Assessments Hub",
        "order": 9999,
        "count": 1
      },
      {
        "label": "Assessments Hub / FInal Examen",
        "order": 9999,
        "count": 1
      },
      {
        "label": "Course material - Lectures",
        "order": 9999,
        "count": 12
      },
      {
        "label": "Course material - Tutorials",
        "order": 9999,
        "count": 2
      },
      {
        "label": "Other useful material",
        "order": 9999,
        "count": 2
      }
    ]
  },
  {
    "slug": "unsw-math-3856",
    "label": "UNSW · MATH 3856",
    "count": 6,
    "subs": [
      {
        "label": "",
        "order": 9999,
        "count": 6
      }
    ]
  }
];
export const knowledgeTotal = 618;
