// AUTO-GENERATED by scripts/ingest-knowledge.ts
export type KnowledgeCategory = { slug: string; label: string; count: number };
export const knowledgeCategories: KnowledgeCategory[] = [
  {
    "slug": "openclaw",
    "label": "OpenClaw",
    "count": 1
  },
  {
    "slug": "unsw-comm-3030",
    "label": "UNSW · COMM 3030",
    "count": 74
  },
  {
    "slug": "unsw-econ-3202",
    "label": "UNSW · ECON 3202",
    "count": 37
  },
  {
    "slug": "unsw-fins-3616",
    "label": "UNSW · FINS 3616",
    "count": 35
  },
  {
    "slug": "unsw-fins-3635",
    "label": "UNSW · FINS 3635",
    "count": 29
  },
  {
    "slug": "unsw-fins-3640",
    "label": "UNSW · FINS 3640",
    "count": 36
  },
  {
    "slug": "unsw-fins-3646",
    "label": "UNSW · FINS 3646",
    "count": 43
  },
  {
    "slug": "unsw-fins-3666",
    "label": "UNSW · FINS 3666",
    "count": 32
  },
  {
    "slug": "unsw-infs-3822",
    "label": "UNSW · INFS 3822",
    "count": 61
  },
  {
    "slug": "unsw-math-1141",
    "label": "UNSW · MATH 1141",
    "count": 5
  },
  {
    "slug": "unsw-math-1241",
    "label": "UNSW · MATH 1241",
    "count": 4
  },
  {
    "slug": "unsw-math-2018",
    "label": "UNSW · MATH 2018",
    "count": 61
  },
  {
    "slug": "unsw-math-2089",
    "label": "UNSW · MATH 2089",
    "count": 1
  },
  {
    "slug": "unsw-math-2901",
    "label": "UNSW · MATH 2901",
    "count": 29
  },
  {
    "slug": "unsw-math-3856",
    "label": "UNSW · MATH 3856",
    "count": 6
  }
];
export const knowledgeTotal = 454;
